[package]
name = "vhost-discovery-tool"
version = "1.3.4"
authors = ["Eugene Lebedev <duke.tougu@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
clap = "2.33"
regex = "1"

serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

log = "0.4.8"
log4rs = "0.10.0"
